# Generated by Django 3.1.3 on 2020-11-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='produits/', verbose_name='Photo du produit 2'),
        ),
    ]
