# Generated by Django 3.1.3 on 2020-11-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201112_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='name',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='sous_titre',
        ),
        migrations.AddField(
            model_name='produit',
            name='designation',
            field=models.CharField(default='', max_length=50, verbose_name='Désignation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence'),
        ),
    ]
