# Generated by Django 3.1.3 on 2020-12-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201208_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activer'),
        ),
    ]
