# Generated by Django 3.1.3 on 2020-12-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactform_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='is_active',
        ),
        migrations.AddField(
            model_name='produit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activer'),
        ),
    ]
