# Generated by Django 3.1.3 on 2020-12-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201208_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['ordre', 'designation'], 'verbose_name': 'Produits', 'verbose_name_plural': 'Produits'},
        ),
    ]
