# Generated by Django 3.1.3 on 2020-12-10 07:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201208_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='description_2',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='partie 2'),
        ),
    ]
