# Generated by Django 3.1.3 on 2020-12-10 07:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_produit_description_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='info_sup',
        ),
        migrations.AddField(
            model_name='produit',
            name='description_1',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='partie 2'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description_2',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='partie 1'),
        ),
    ]
