# Generated by Django 3.1.3 on 2020-12-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201210_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='designation',
            field=models.CharField(max_length=150, verbose_name='Désignation'),
        ),
    ]
