# Generated by Django 3.1.3 on 2020-12-20 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_marque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='Marque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.marque'),
        ),
    ]
