# Generated by Django 3.1.3 on 2020-12-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_produit_marque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='Marque',
            new_name='marque',
        ),
    ]
