# Generated by Django 3.1.3 on 2020-12-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201221_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_month',
        ),
    ]
