# Generated by Django 3.1.3 on 2021-03-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_post_created_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.CharField(choices=[('IN', 'Intrusion'), ('IC', 'Incendie Conventionnelle'), ('IA', 'Incendie Adressable'), ('C4', 'Cables'), ('C5', 'Categorie Y')], default='IN', max_length=2),
        ),
    ]
