# Generated by Django 3.1.3 on 2021-03-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210327_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=150)),
                ('fichier', models.FileField(max_length=180, upload_to='catalogues')),
            ],
        ),
    ]
