# Generated by Django 3.1.3 on 2021-04-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210327_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.CharField(choices=[('IN', 'Intrusion'), ('IC', 'Incendie Conventionnelle'), ('IA', 'Incendie Adressable'), ('C4', 'Câble & Energie'), ('C5', 'Categorie Y')], default='IN', max_length=2),
        ),
    ]
